# Generated by Django 2.0.7 on 2022-01-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('description', models.TextField()),
                ('prix', models.TextField()),
                ('sommaire', models.TextField(default='cool')),
            ],
        ),
    ]
