# Generated by Django 2.0.7 on 2022-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sommaire',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='titre',
            field=models.CharField(max_length=120),
        ),
    ]
