# Generated by Django 2.0.7 on 2022-01-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220112_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sommaire',
            field=models.TextField(),
        ),
    ]
