# Generated by Django 2.0.7 on 2022-01-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220112_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prix',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sommaire',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='titre',
            new_name='title',
        ),
    ]
